name: Resize images

on:
  pull_request:
    paths:
      - 'public/home/**.jpg'
      - 'public/home/**.jpeg'
      - 'public/home/**.png'
jobs:
  build:
    name: Image Resizer Inplace Limit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Resize Images
        id: resize-images
        uses: petems/image-resizer-gh-action@master
        with:
          target: public/home/ # directory to look for images in
          dimensions: 300 # parameter to change size
          widthLimit: 500 # max width to check
          heightLimit: 800 # max height to check

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: 'public/home/'
          author_name: "github-actions[bot]"
          author_email: "github-actions@users.noreply.github.com"
          message: |
            Images Reszied by Github action\n
            ```
            ${{steps.resize-images.outputs.images_changed}}
            ```
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
